import type { BuilderConfig } from "@/types/builder";

export function exportToJson(config: BuilderConfig): string {
  return JSON.stringify(config, null, 2);
}

export function exportToMarkdown(config: BuilderConfig): string {
  let md = `# ${config.brandName}\n\n`;
  md += `> ${config.tagline}\n\n`;
  md += `${config.subtitle}\n\n`;
  md += `**Primary CTA:** ${config.ctaLabel} | **Secondary CTA:** ${config.ctaSecondaryLabel}\n\n`;
  md += `---\n\n`;

  config.sectionOrder.forEach((section) => {
    switch (section) {
      case "features":
        md += `## Features\n`;
        config.features.forEach((f) => {
          md += `- **${f.title}**: ${f.description}\n`;
        });
        md += `\n`;
        break;
      case "stats":
        md += `## Statistics\n`;
        config.stats.forEach((s) => {
          md += `- **${s.label}**: ${s.value}\n`;
        });
        md += `\n`;
        break;
      case "testimonials":
        md += `## Testimonials\n`;
        config.testimonials.forEach((t) => {
          md += `> "${t.quote}"\n> — **${t.author}**, ${t.role}\n\n`;
        });
        break;
      case "pricing":
        md += `## Pricing\n`;
        config.pricing.forEach((p) => {
          md += `### ${p.name} - ${p.price}/mo ${p.isPopular ? "(Most Popular)" : ""}\n`;
          md += `${p.description}\n`;
          p.features.forEach((f) => {
            md += `- ${f}\n`;
          });
          md += `\n`;
        });
        break;
      case "faq":
        md += `## Frequently Asked Questions\n`;
        config.faqs.forEach((f) => {
          md += `**Q: ${f.question}**\nA: ${f.answer}\n\n`;
        });
        break;
    }
  });

  return md.trim();
}

export function exportToReact(config: BuilderConfig): string {
  const isDark = config.darkMode;
  const bg = isDark ? "bg-black text-white" : "bg-white text-slate-900";
  const primary = config.primaryColor;
  const radius = config.borderRadius === "none" ? "rounded-none" : config.borderRadius === "full" ? "rounded-full" : "rounded-xl";

  return `// Generated by UI Builder
import React from "react";

export default function LandingPage() {
  return (
    <div className="min-h-screen ${bg} font-${config.font}">
      {/* Navigation */}
      <nav className="border-b ${isDark ? 'border-white/10' : 'border-slate-200'} p-4 flex justify-between items-center max-w-7xl mx-auto">
        <div className="font-bold text-xl">${config.brandName}</div>
        <button className="px-4 py-2 ${radius} text-white font-medium" style={{ backgroundColor: "${primary}" }}>
          ${config.ctaLabel}
        </button>
      </nav>

      {/* Hero Section */}
      <header className="py-24 text-center px-4 max-w-4xl mx-auto">
        <div className="inline-block px-3 py-1 mb-6 text-sm font-semibold rounded-full bg-slate-500/10 text-slate-500">
          ${config.tagline}
        </div>
        <h1 className="text-5xl md:text-7xl font-black tracking-tight mb-8">
          The future of ${config.brandName}
        </h1>
        <p className="text-xl md:text-2xl ${isDark ? 'text-white/60' : 'text-slate-600'} mb-12">
          ${config.subtitle}
        </p>
        <div className="flex justify-center gap-4">
          <button className="px-8 py-4 ${radius} text-white font-bold text-lg hover:opacity-90" style={{ backgroundColor: "${primary}" }}>
            ${config.ctaLabel}
          </button>
          <button className="px-8 py-4 ${radius} font-bold text-lg border ${isDark ? 'border-white/20 hover:bg-white/5' : 'border-slate-200 hover:bg-slate-50'}">
            ${config.ctaSecondaryLabel}
          </button>
        </div>
      </header>

      {/* Features Grid */}
      <section className="py-24 max-w-7xl mx-auto px-4">
        <div className="grid md:grid-cols-3 gap-8">
${config.features.map(f => `          <div className="p-8 ${isDark ? 'bg-white/5' : 'bg-slate-50'} ${radius}">
            <h3 className="text-xl font-bold mb-4">${f.title}</h3>
            <p className="${isDark ? 'text-white/60' : 'text-slate-600'}">${f.description}</p>
          </div>`).join('\n')}
        </div>
      </section>

      {/* Pricing */}
      <section className="py-24 max-w-7xl mx-auto px-4">
        <div className="grid md:grid-cols-3 gap-8">
${config.pricing.map(p => `          <div className="p-8 border ${isDark ? 'border-white/10' : 'border-slate-200'} ${radius} ${p.isPopular ? 'ring-2' : ''}" style={{ ${p.isPopular ? `ringColor: "${primary}"` : ''} }}>
            <h3 className="text-xl font-bold mb-2">${p.name}</h3>
            <div className="text-4xl font-black mb-6">${p.price}<span className="text-sm font-medium opacity-60">/mo</span></div>
            <p className="mb-8 opacity-70">${p.description}</p>
            <button className="w-full py-3 ${radius} font-bold ${p.isPopular ? 'text-white' : ''}" style={{ backgroundColor: "${p.isPopular ? primary : (isDark ? '#333' : '#eee')}" }}>
              Get Started
            </button>
          </div>`).join('\n')}
        </div>
      </section>
      
      {/* Footer */}
      <footer className="border-t ${isDark ? 'border-white/10' : 'border-slate-200'} py-12 text-center opacity-60">
        <p>© {new Date().getFullYear()} ${config.brandName}. All rights reserved.</p>
      </footer>
    </div>
  );
}
`;
}
